### ISSUE TITLE
Странная реакция на клик

### ISSUE THREAD

**Issue by yuchiko** [IgorPototskyi/site-tajam#1]
при клике на меню, оно у тебя сворачивается и разворачивается, глянь че так

**Comment by IgorPototskyi** [comment]
Дело в атрибутах ссылок 'data-toggle="collapse" data-target=".navbar-collapse"'. Использовал для того, чтоб выпадающее меню при клике по элементу навигации сворачивалось. Учитывая то, что навигация сайта будет вести на другие страницы, ничего сворачивать не надо. Убрал.
